version: 2

jobs:
#  lint:
#    docker:
#      - image: python:3.6
#    steps:
#      - checkout
#      - run: pip install tox
#      - run: tox -e "flake8"
  build:
    docker:
      - image: python:3.6
        environment:
          DJANGO_DB_USER: hymaintenance
          DJANGO_DB: circle_test
          DJANGO_DB_PASSWORD: password

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: hymaintenance
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz && rm dockerize-linux-amd64-v0.6.1.tar.gz
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 120s
      - run: pip install tox
      - run: pip install coveralls
      - run: tox -e "flake8"
      - run: tox -e "py36-django2.0"
      - run: coveralls
#
#workflows:
#  version: 2
#  lint-and-test:
#    jobs:
#      - lint-and-py36:
