version: 2

jobs:
#  lint:
#    docker:
#      - image: python:3.6
#    steps:
#      - checkout
#      - run: pip install tox
#      - run: tox -e "flake8"
  build:
    docker:
      - image: python:3.6
    environment:
       COVERALLS_REPO_TOKEN: rVivfLB1a620q6D2kpgCgS71IZurNllL5
       HYMAINTENANCE_SECRET_KEY: NotThatSecret
    steps:
      - checkout
      - run: pip install tox coveralls
      - run: tox -e "flake8"
      - run: tox -e "sqlite"
      - run: coveralls
#
#workflows:
#  version: 2
#  lint-and-test:
#    jobs:
#      - lint-and-py36:
