# Generated by Django 2.0.1 on 2018-02-27 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0002_maintenancetype_visible")]

    operations = [
        migrations.AlterField(
            model_name="maintenanceconsumer",
            name="company",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="customers.Company"),
        ),
        migrations.AlterField(
            model_name="maintenancecontract",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="customers.Company", verbose_name="Company"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancecontract",
            name="maintenance_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="maintenance.MaintenanceType"),
        ),
        migrations.AlterField(
            model_name="maintenancecredit",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="customers.Company", verbose_name="Company"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancecredit",
            name="maintenance_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="maintenance.MaintenanceType"),
        ),
        migrations.AlterField(
            model_name="maintenanceissue",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="customers.Company", verbose_name="Company"
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceissue",
            name="consumer_who_ask",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumers_who_asked",
                to="maintenance.MaintenanceConsumer",
                verbose_name="Who ask the question ?",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceissue",
            name="incoming_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="maintenance.IncomingChannel",
                verbose_name="Incoming Channel",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceissue",
            name="maintenance_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="maintenance.MaintenanceType"),
        ),
        migrations.AlterField(
            model_name="maintenanceissue",
            name="user_who_fix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users_who_fixed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Who fix the issue ? ",
            ),
        ),
    ]
