# Generated by Django 2.0.1 on 2018-02-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20180227_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecontract',
            name='total_type',
            field=models.IntegerField(choices=[(0, 'Available total time'), (1, 'Remaining total time')], default=1, verbose_name='Counter type'),
        ),
    ]
