# Generated by Django 2.0.1 on 2018-02-28 10:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0004_auto_20180228_1028")]

    operations = [
        migrations.AlterField(
            model_name="maintenancecontract",
            name="visible",
            field=models.BooleanField(default=True, verbose_name="Visible to managers"),
        )
    ]
