# Generated by Django 2.0.1 on 2018-02-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenancecontract_total_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancecontract',
            name='total_type',
            field=models.IntegerField(choices=[(0, 'Available total time'), (1, 'Consummed total time')], default=0, verbose_name='Counter type'),
        ),
    ]
