# Generated by Django 2.0.1 on 2018-03-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0005_auto_20180228_1126")]

    operations = [
        migrations.RenameField(model_name="maintenancetype", old_name="visible", new_name="default_visibility")
    ]
