# Generated by Django 2.0.1 on 2018-03-02 09:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0008_auto_20180301_1505")]

    operations = [
        migrations.AddField(
            model_name="maintenancecontract",
            name="total_type",
            field=models.IntegerField(
                choices=[(0, "Available total time"), (1, "Consummed total time")],
                default=0,
                verbose_name="Counter type",
            ),
        )
    ]
