# Generated by Django 2.0.3 on 2018-03-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_auto_20180315_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetype',
            name='label_for_company_detailview',
        ),
    ]
