# Generated by Django 2.0.3 on 2018-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_auto_20180315_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecontract',
            name='counter_name',
            field=models.CharField(default='', max_length=255, verbose_name='Name of counter'),
        ),
    ]
