# Generated by Django 2.0.3 on 2018-03-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_remove_maintenancetype_label_for_company_detailview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetype',
            name='css_class',
        ),
    ]
