# Generated by Django 2.0.3 on 2018-03-30 11:25

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0013_maintenancecontract_counter_name")]

    operations = [
        migrations.AlterField(
            model_name="maintenancecontract",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="customers.Company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancecontract",
            name="maintenance_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="contracts", to="maintenance.MaintenanceType"
            ),
        ),
    ]
