# Generated by Django 2.0.3 on 2018-04-06 13:06

from django.db import migrations


def do_nothing(apps, schema_editor):
    pass


def create_missing_issue_numbers(apps, schema_editor):
    Company = apps.get_model("customers", "Company")
    MaintenanceIssue = apps.get_model("maintenance", "MaintenanceIssue")
    companies = Company.objects.all()
    for company in companies:
        company.issues_counter = 0
        issues = MaintenanceIssue.objects.filter(company=company).order_by("id")
        for issue in issues:
            company.issues_counter += 1
            issue.number = company.issues_counter
            issue.save()
        company.save()


class Migration(migrations.Migration):

    dependencies = [("customers", "0006_company_issues_counter"), ("maintenance", "0018_maintenanceissue_number")]

    operations = [migrations.RunPython(create_missing_issue_numbers, do_nothing)]
