# Generated by Django 2.0.3 on 2018-04-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_create_missing_issue_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceissue',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
