# Generated by Django 2.0.3 on 2018-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_company_issues_counter'),
        ('maintenance', '0020_auto_20180406_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceissue',
            options={'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterField(
            model_name='maintenanceissue',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Issue number'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceissue',
            unique_together={('number', 'company')},
        ),
    ]
