# Generated by Django 2.0.3 on 2018-04-16 13:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0022_auto_20180406_1555")]

    operations = [
        migrations.AddField(
            model_name="maintenanceissue",
            name="context_description_file",
            field=models.FileField(null=True, upload_to="uploads/None/"),
        ),
        migrations.AddField(
            model_name="maintenanceissue",
            name="resolution_description_file",
            field=models.FileField(null=True, upload_to="uploads/{company.name}/"),
        ),
    ]
