# Generated by Django 2.0.3 on 2018-04-17 08:27

from django.db import migrations, models

import maintenance.models.issue


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_auto_20180416_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceissue',
            name='context_description_file',
            field=models.FileField(null=True, upload_to=maintenance.models.issue._get_context_file_path),
        ),
        migrations.AlterField(
            model_name='maintenanceissue',
            name='resolution_description_file',
            field=models.FileField(null=True, upload_to=maintenance.models.issue._get_resolution_file_path),
        ),
    ]
