# Generated by Django 2.0.3 on 2018-04-27 13:46

from django.db import migrations, models

import maintenance.models.issue


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_auto_20180424_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceissue',
            name='context_description_file',
            field=models.FileField(max_length=200, null=True, storage=maintenance.models.issue.MaintenanceIssueAttachmentStorage(), upload_to=maintenance.models.issue._get_context_file_path),
        ),
        migrations.AlterField(
            model_name='maintenanceissue',
            name='resolution_description_file',
            field=models.FileField(max_length=200, null=True, storage=maintenance.models.issue.MaintenanceIssueAttachmentStorage(), upload_to=maintenance.models.issue._get_resolution_file_path),
        ),
    ]
