# Generated by Django 2.0.3 on 2018-07-05 13:08

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0027_maintenanceconsumer_is_used")]

    operations = [
        migrations.AlterField(
            model_name="maintenancecredit",
            name="date",
            field=models.DateField(default=datetime.date.today, verbose_name="Date of Action"),
        )
    ]
