# Generated by Django 2.0.3 on 2018-08-01 15:04

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0028_auto_20180705_1508")]

    operations = [
        migrations.AddField(
            model_name="maintenanceissue",
            name="contract",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="maintenance.MaintenanceContract"
            ),
        )
    ]
