# Generated by Django 2.0.3 on 2018-08-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0030_bound_issue_and_contract")]

    operations = [migrations.RemoveField(model_name="maintenanceissue", name="maintenance_type")]
