# Generated by Django 2.0.3 on 2018-08-02 09:28

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0031_remove_maintenanceissue_maintenance_type")]

    operations = [
        migrations.AlterField(
            model_name="maintenanceissue",
            name="contract",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="maintenance.MaintenanceContract"),
        )
    ]
