# Generated by Django 2.0.3 on 2018-08-02 09:28

from django.db import migrations


def do_nothing(apps, schema_editor):
    pass


def link_credits_with_corresponding_contracts(apps, schema_editor):
    MaintenanceCredit = apps.get_model("maintenance", "MaintenanceCredit")
    MaintenanceContract = apps.get_model("maintenance", "MaintenanceContract")

    for credit in MaintenanceCredit.objects.all():
        contract = MaintenanceContract.objects.filter(
            company=credit.company, maintenance_type=credit.maintenance_type
        ).first()
        credit.contract = contract
        credit.save()


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0033_maintenancecredit_contract")]

    operations = [migrations.RunPython(link_credits_with_corresponding_contracts, do_nothing)]
