# Generated by Django 2.0.8 on 2018-09-10 13:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0036_auto_20180830_1513")]

    operations = [
        migrations.AddField(
            model_name="maintenancecontract",
            name="number_hours_min",
            field=models.IntegerField(default=0, verbose_name="Credited hours Threshold"),
        )
    ]
