# Generated by Django 2.0.8 on 2018-09-10 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0037_maintenancecontract_number_hours_min"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancecontract",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referent_for",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
