# Generated by Django 2.0.8 on 2018-09-24 13:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0038_maintenancecontract_recipient")]

    operations = [
        migrations.AddField(
            model_name="maintenancecontract",
            name="email_alert",
            field=models.BooleanField(default=False, verbose_name="Email alert"),
        )
    ]
