# Generated by Django 2.0.8 on 2018-11-26 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0040_auto_20181114_1654")]

    operations = [
        migrations.AlterField(
            model_name="maintenancecontract",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": False, "is_superuser": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referent_for",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
