# Generated by Django 2.0.8 on 2018-12-17 15:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0041_auto_20181126_1443")]

    operations = [
        migrations.CreateModel(
            name="MaintenanceCreditChoices",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.IntegerField(verbose_name="Value")),
            ],
        )
    ]
