# Generated by Django 2.0.8 on 2018-12-17 15:30

from django.db import migrations


def do_nothing(apps, schema_editor):
    pass


def create_maintenance_credit_choices(apps, schema_editor):
    maintenanceCreditChoices = apps.get_model("maintenance", "MaintenanceCreditChoices")
    hours_step = 8
    for value in range(hours_step, 6 * hours_step, hours_step):
        maintenanceCreditChoices.objects.create(value=value)


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0042_maintenancecreditchoices")]

    operations = [migrations.RunPython(create_maintenance_credit_choices, do_nothing)]
