# Generated by Django 2.0.8 on 2019-01-14 14:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0043_auto_20181217_1630")]

    operations = [
        migrations.AddField(
            model_name="maintenancecredit",
            name="subject",
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Subject"),
        )
    ]
