# Generated by Django 2.0.8 on 2019-01-28 09:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0044_maintenancecredit_subject")]

    operations = [
        migrations.AlterField(
            model_name="maintenancecontract",
            name="number_hours",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Credited hours"),
        ),
        migrations.AlterField(
            model_name="maintenanceissue",
            name="subject",
            field=models.CharField(default="a question", max_length=500, verbose_name="Subject"),
        ),
    ]
