# Generated by Django 2.0.8 on 2019-02-06 15:49

from django.db import migrations
from django.db import models


def do_nothing(apps, schema_editor):
    pass


def update_number_hours(apps, schema_editor):
    MaintenanceContract = apps.get_model("maintenance", "MaintenanceContract")
    MaintenanceCredit = apps.get_model("maintenance", "MaintenanceCredit")

    for contract in MaintenanceContract.objects.all():
        if contract.number_hours is not None and contract.number_hours > 0:
            MaintenanceCredit.objects.create(
                company=contract.company, contract=contract, date=contract.start, hours_number=contract.number_hours
            )
        hours_sum = MaintenanceCredit.objects.filter(contract=contract).aggregate(models.Sum("hours_number"))
        hours_sum = hours_sum["hours_number__sum"]
        if hours_sum is None:
            hours_sum = 0
        contract.number_hours = hours_sum
        contract.save()


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0045_auto_20190128_1051")]

    operations = [migrations.RunPython(update_number_hours, do_nothing)]
