# Generated by Django 2.0.13 on 2019-03-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0046_auto_20190206_1649")]

    operations = [
        migrations.RenameField(model_name="maintenancecontract", old_name="number_hours", new_name="credited_hours"),
        migrations.RenameField(
            model_name="maintenancecontract", old_name="number_hours_min", new_name="credited_hours_min"
        ),
    ]
