# Generated by Django 2.0.13 on 2019-03-19 10:10

from django.db import migrations
from django.db import models


def do_nothing(apps, schema_editor):
    pass


def update_consumed_minutes(apps, schema_editor):
    MaintenanceContract = apps.get_model("maintenance", "MaintenanceContract")
    MaintenanceIssue = apps.get_model("maintenance", "MaintenanceIssue")

    for contract in MaintenanceContract.objects.all():
        minutes_sum = MaintenanceIssue.objects.filter(contract=contract, is_deleted=False).aggregate(
            models.Sum("number_minutes")
        )
        minutes_sum = minutes_sum["number_minutes__sum"]
        if minutes_sum is None:
            minutes_sum = 0
        contract.consumed_minutes = minutes_sum
        contract.save()


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0049_auto_20190318_1730")]

    operations = [migrations.RunPython(update_consumed_minutes, do_nothing)]
