# Generated by Django 2.0.13 on 2019-04-03 13:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0053_auto_20190403_1524")]

    operations = [
        migrations.AddField(
            model_name="maintenancecontract",
            name="recurrence_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Credit-recurrence start date"),
        ),
        migrations.AlterField(
            model_name="maintenancecontract",
            name="credit_recurrence",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Monthly credit"), (1, "Annual credit")],
                null=True,
                verbose_name="Recurrence period",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancecontract",
            name="recurrence_last_date",
            field=models.DateField(blank=True, null=True, verbose_name="Credit-recurrence last date"),
        ),
        migrations.AlterField(
            model_name="maintenancecontract",
            name="recurrence_next_date",
            field=models.DateField(blank=True, null=True, verbose_name="Credit-recurrence next date"),
        ),
    ]
