# Generated by Django 2.0.13 on 2019-04-08 08:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0054_auto_20190403_1537")]

    operations = [
        migrations.AddField(
            model_name="maintenancecontract",
            name="has_credit_recurrence",
            field=models.BooleanField(default=False, verbose_name="Recurrence"),
        )
    ]
