# Generated by Django 2.0.13 on 2019-04-19 08:16

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("maintenance", "0055_maintenancecontract_has_credit_recurrence")]

    operations = [
        migrations.AlterField(
            model_name="maintenancecontract",
            name="credit_recurrence",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Monthly credit"), (1, "Annual credit")],
                null=True,
                verbose_name="Credit-recurrence frequency",
            ),
        )
    ]
