# Generated by Django 3.2.13 on 2022-06-13 08:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0056_auto_20190419_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecontract',
            name='has_reset_recurrence',
            field=models.BooleanField(default=False, verbose_name='Automatic counter reset'),
        ),
    ]
