# Generated by Django 2.0.1 on 2018-02-27 08:34

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("customers", "0002_remove_company_name_for_site")]

    operations = [
        migrations.AlterField(
            model_name="maintenanceuser",
            name="company",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="customers.Company"
            ),
        )
    ]
