# Generated by Django 2.0.3 on 2018-03-30 13:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("customers", "0004_auto_20180306_1051")]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="maintenance_contact",
            field=models.CharField(max_length=500, verbose_name="name of internal contact"),
        )
    ]
