# Generated by Django 2.0.3 on 2018-04-06 13:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("customers", "0005_auto_20180330_1521")]

    operations = [
        migrations.AddField(model_name="company", name="issues_counter", field=models.PositiveIntegerField(default=0))
    ]
