# Generated by Django 2.0.3 on 2018-04-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_company_issues_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug_name',
            field=models.SlugField(null=True),
        ),
    ]
