# Generated by Django 2.0.3 on 2018-04-10 10:19

from django.db import migrations
from django.utils.text import slugify


def do_nothing(apps, schema_editor):
    pass


def create_missing_company_slugname(apps, schema_editor):
    Company = apps.get_model("customers", "Company")
    companies = Company.objects.all()
    for company in companies:
        company.slug_name = slugify(company.name)[:49]
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_company_slug_name'),
    ]

    operations = [
        migrations.RunPython(create_missing_company_slugname, do_nothing),
    ]
