# Generated by Django 2.0.3 on 2018-04-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_create_missing_company_slugname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug_name',
            field=models.SlugField(),
        ),
    ]
