# Generated by Django 2.0.3 on 2018-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20180410_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug_name',
            field=models.SlugField(editable=False),
        ),
    ]
