# Generated by Django 2.0.3 on 2018-04-10 15:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("customers", "0011_auto_20180410_1542")]

    operations = [
        migrations.AlterField(
            model_name="company", name="slug_name", field=models.SlugField(editable=False, max_length=255, unique=True)
        )
    ]
