# Generated by Django 2.0.2 on 2018-04-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20180410_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceuser',
            name='operator_for',
            field=models.ManyToManyField(blank=True, related_name='managed_by', to='customers.Company', verbose_name='Managed Companies'),
        ),
    ]
