# Generated by Django 2.0.3 on 2018-07-24 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("customers", "0013_maintenanceuser_operator_for")]

    operations = [
        migrations.AddField(
            model_name="company",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact_of",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
