# Generated by Django 2.0.3 on 2018-07-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("customers", "0014_company_contact")]

    operations = [migrations.RemoveField(model_name="company", name="maintenance_contact")]
