# Generated by Django 2.0.3 on 2018-07-30 13:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("customers", "0016_auto_20180725_1012")]

    operations = [
        migrations.AddField(
            model_name="maintenanceuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="phone number"),
        )
    ]
