# Generated by Django 2.0.8 on 2018-08-30 13:13

import customers.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("customers", "0017_maintenanceuser_phone")]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact_of",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="company", name="name", field=models.CharField(max_length=255, verbose_name="Name")
        ),
        migrations.AlterField(
            model_name="maintenanceuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="customers.Company",
                verbose_name="User's company",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceuser",
            name="email",
            field=customers.fields.LowerCaseEmailField(
                db_index=True,
                error_messages={"unique": "A user with that email already exists."},
                max_length=254,
                unique=True,
                verbose_name="Email address",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="maintenanceuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",  # noqa : E501
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="Staff",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Last name"),
        ),
    ]
