# Generated by Django 2.0.8 on 2018-11-26 13:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("customers", "0018_auto_20180830_1513")]

    operations = [
        migrations.AddField(
            model_name="company", name="is_archived", field=models.BooleanField(default=False, verbose_name="Archived")
        )
    ]
