# Generated by Django 2.0.8 on 2019-01-16 15:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("customers", "0020_auto_20181130_1006")]

    operations = [
        migrations.AddField(
            model_name="company",
            name="dark_font_color",
            field=models.BooleanField(default=False, verbose_name="Dark or light font color"),
        )
    ]
