# Generated by Django 2.0.8 on 2019-01-28 09:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("customers", "0021_company_dark_font_color")]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="dark_font_color",
            field=models.BooleanField(default=False, verbose_name="Font color"),
        )
    ]
