# Generated by Django 2.0.8 on 2019-02-15 09:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("customers", "0022_auto_20190128_1051")]

    operations = [
        migrations.AddField(
            model_name="company", name="displayed_month_number", field=models.PositiveIntegerField(default=6)
        )
    ]
