# Generated by Django 3.2.13 on 2022-05-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_company_displayed_month_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceuser',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
