# Generated by Django 2.0.8 on 2018-08-30 13:13

from django.db import migrations
from django.db import models

import customers.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralInformation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("email", customers.fields.LowerCaseEmailField(max_length=255, verbose_name="Email address")),
                ("address", models.TextField(verbose_name="postal address")),
                ("website", models.URLField(max_length=255, verbose_name="Website")),
                ("phone", models.CharField(blank=True, max_length=25, null=True, verbose_name="phone number")),
            ],
        )
    ]
