# Generated by Django 2.0.8 on 2018-08-31 13:15

from django.db import migrations


def do_nothing(apps, schema_editor):
    pass


def create_general_information_object(apps, schema_editor):
    info = apps.get_model("high_ui", "GeneralInformation")
    info.objects.create(
        name="company",
        email="company@email.com",
        website="company.com",
        address="company address",
        phone="00 00 00 00 00",
    )


class Migration(migrations.Migration):

    dependencies = [("high_ui", "0001_initial")]

    operations = [migrations.RunPython(create_general_information_object, do_nothing)]
