# Generated by Django 2.0.8 on 2019-02-18 10:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("high_ui", "0002_create_general_info_object")]

    operations = [
        migrations.AlterField(
            model_name="generalinformation",
            name="website",
            field=models.CharField(max_length=255, verbose_name="Website"),
        )
    ]
